import React,{useEffect,useMemo,useState}from"react";import{Link,useParams}from"react-router-dom";import{api}from"../lib/api";import{Badge,Card,Empty,Field}from"../components/UI";
export default function GameDetail(){
  const{slug}=useParams();
  const[game,setGame]=useState(null),[characters,setCharacters]=useState([]),[domains,setDomains]=useState([]),[equipment,setEquipment]=useState([]),[materials,setMaterials]=useState([]),[q,setQ]=useState("");
  useEffect(()=>{api.get(`/games/${slug}`,{auth:false}).then(async r=>{setGame(r.game);const[c,d,e,m]=await Promise.all([api.get(`/characters?gameId=${r.game.id}&pageSize=100`,{auth:false}),api.get(`/catalog/domains?gameId=${r.game.id}`,{auth:false}),api.get(`/catalog/equipment?gameId=${r.game.id}`,{auth:false}),api.get(`/catalog/materials?gameId=${r.game.id}`,{auth:false})]);setCharacters(c.characters||[]);setDomains(d.domains||[]);setEquipment(e.equipment||[]);setMaterials(m.materials||[])})},[slug]);
  const shown=useMemo(()=>characters.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())),[characters,q]);
  if(!game)return <div className="section">Loading…</div>;
  return <section className="section"><div className="titleRow"><div><p className="eyebrow">{game.franchise||"GAME"}</p><h1>{game.name}</h1></div><span className="gameDot large" style={{background:game.accent_color}}/></div><div className="tabsLine"><a href="#characters">Characters</a><a href="#gear">Equipment</a><a href="#materials">Materials</a><a href="#farm">{game.entity_schema?.domainWord||"Farming"}</a><Link to={`/maps?gameId=${game.id}`}>Map</Link></div>
  <h2 id="characters">Characters</h2><Field label="Search roster" placeholder="Type a character name" value={q} onChange={e=>setQ(e.target.value)}/>{shown.length?<div className="grid chars">{shown.map(c=><Link to={`/characters/${c.id}`} key={c.id}><Card><div className="titleRow"><h3>{c.name}</h3>{c.tier&&<Badge>{c.tier} Tier</Badge>}</div><p>{Object.values(c.stats||{}).slice(0,4).filter(Boolean).join(" • ")}</p></Card></Link>)}</div>:<Empty title="No reviewed characters" body="The database is ready; add verified entries from the admin side."/>}
  <h2 id="gear">Equipment & artifact sets</h2>{equipment.length?<div className="resourceGrid">{equipment.map(e=><Card key={e.id}><div className="titleRow"><h3>{e.name}</h3>{e.rarity&&<Badge>{e.rarity}★</Badge>}</div><p>{e.kind.replaceAll("_"," ")}{e.stats?.weaponType?` • ${e.stats.weaponType}`:""}{e.stats?.secondaryStat?` • ${e.stats.secondaryStat}`:""}</p>{e.stats?.twoPiece&&<small>2-piece: {e.stats.twoPiece}</small>}{e.effect_text&&<small className="blockNote">{e.effect_text}</small>}</Card>)}</div>:<Empty title="No equipment yet" body="Reviewed equipment has not been added for this game."/>}
  <h2 id="materials">Materials</h2>{materials.length?<div className="resourceGrid">{materials.map(m=><Card key={m.id}><div className="titleRow"><h3>{m.name}</h3>{m.rarity&&<Badge>{m.rarity}★</Badge>}</div><p>{m.category||"Material"}</p>{m.source_locations?.length&&<small>{m.source_locations.join(" • ")}</small>}</Card>)}</div>:<Empty title="No materials yet" body="Reviewed materials have not been added for this game."/>}
  <h2 id="farm">{game.entity_schema?.domainWord||"Farming"}</h2>{domains.length?<div className="list">{domains.map(d=><Card key={d.id}><b>{d.name}</b><p>{d.location||""} {d.available_days?.length?`• ${d.available_days.join(", ")}`:""}</p><small>{d.drops}</small></Card>)}</div>:<Empty title="No farming locations yet" body="Add reviewed domains/stages through the backend."/>}</section>
}
